"""Physics-first LightGBM + PSO integration for Radiocity."""
from __future__ import annotations

from dataclasses import dataclass
import numpy as np

from radiocity.lightgbm_surrogate import LightGBMSurrogate
from radiocity.model import RadiationChannel, SystemParameters, simulate_step
from radiocity.pso_optimizer import particle_swarm_optimize

@dataclass(frozen=True)
class OptimizationResult:
    wavelength_min_m: float
    wavelength_max_m: float
    predicted_useful_power_w: float
    validated_useful_power_w: float
    validated_temperature_k: float
    thermal_constraint_satisfied: bool


def _row(source_k: float, receiver_k: float, lo: float, hi: float, c: float, v: float, e: float, f: float, area: float) -> np.ndarray:
    return np.array([[source_k, receiver_k, lo, hi, c, v, e, f, area]], dtype=float)


def train_physics_surrogate(channel: RadiationChannel, receiver_temperature_k: float, samples: int = 300, seed: int = 42) -> LightGBMSurrogate:
    """Train LightGBM directly from samples generated by the Planck model."""
    if channel.source_temperature_k is None:
        raise ValueError("A thermal source temperature is required.")
    rng = np.random.default_rng(seed)
    rows, targets = [], []
    for _ in range(samples):
        lo = rng.uniform(channel.wavelength_min_m, channel.wavelength_max_m * 0.8)
        hi = rng.uniform(lo * 1.05, channel.wavelength_max_m)
        candidate = RadiationChannel(
            channel.name, channel.incident_power_w_m2, channel.area_m2,
            channel.capture_efficiency, channel.conversion_efficiency,
            channel.source_temperature_k, channel.emissivity, channel.view_factor, lo, hi,
        )
        rows.append(_row(channel.source_temperature_k, receiver_temperature_k, lo, hi, channel.capture_efficiency, channel.conversion_efficiency, channel.emissivity, channel.view_factor, channel.area_m2)[0])
        targets.append(candidate.useful_power(receiver_temperature_k))
    return LightGBMSurrogate().fit(np.asarray(rows), np.asarray(targets))


def optimize_spectral_channel(channel: RadiationChannel, system: SystemParameters, receiver_temperature_k: float, storage_j: float, dt_s: float = 1.0, training_samples: int = 300, pso_particles: int = 24, pso_iterations: int = 60, seed: int = 42) -> OptimizationResult:
    """Use LightGBM as a fast surrogate, PSO for search, and physics for validation."""
    surrogate = train_physics_surrogate(channel, receiver_temperature_k, training_samples, seed)
    lo_um, hi_um = channel.wavelength_min_m * 1e6, channel.wavelength_max_m * 1e6

    def bounds(x: np.ndarray) -> tuple[float, float]:
        center, width = x
        lo = max(lo_um, center - width / 2)
        hi = min(hi_um, center + width / 2)
        return lo * 1e-6, max(lo * 1.001e-6, hi * 1e-6)

    def objective(x: np.ndarray) -> float:
        lo, hi = bounds(x)
        predicted = float(surrogate.predict(_row(channel.source_temperature_k or 0.0, receiver_temperature_k, lo, hi, channel.capture_efficiency, channel.conversion_efficiency, channel.emissivity, channel.view_factor, channel.area_m2))[0])
        candidate = RadiationChannel(channel.name, channel.incident_power_w_m2, channel.area_m2, channel.capture_efficiency, channel.conversion_efficiency, channel.source_temperature_k, channel.emissivity, channel.view_factor, lo, hi)
        state = simulate_step((candidate,), system, storage_j, receiver_temperature_k, dt_s)
        excess = max(0.0, state["temperature_k"] - system.maximum_temperature_k)
        return -predicted + 1e6 * excess

    result = particle_swarm_optimize(objective, np.array([(lo_um + hi_um) / 2, max((hi_um - lo_um) * .02, .01)]), np.array([hi_um, hi_um - lo_um]), particles=pso_particles, iterations=pso_iterations, seed=seed)
    lo, hi = bounds(result.position)
    candidate = RadiationChannel(channel.name, channel.incident_power_w_m2, channel.area_m2, channel.capture_efficiency, channel.conversion_efficiency, channel.source_temperature_k, channel.emissivity, channel.view_factor, lo, hi)
    state = simulate_step((candidate,), system, storage_j, receiver_temperature_k, dt_s)
    predicted = float(surrogate.predict(_row(channel.source_temperature_k, receiver_temperature_k, lo, hi, channel.capture_efficiency, channel.conversion_efficiency, channel.emissivity, channel.view_factor, channel.area_m2))[0])
    return OptimizationResult(lo, hi, predicted, state["useful_power_w"], state["temperature_k"], state["temperature_k"] <= system.maximum_temperature_k)
